### PR TITLE
Adding pylint CI checks

### LINKED ISSUE #392: CI: code style checks
Beyond just enforcing `black` code style, we also want to run some extra CI checks to flag bad practices like:
- `import *` 
- imports that are unused in the code

Some of these may be best addressed via tools like:
 
https://launchpad.net/pyflakes
https://pylint.pycqa.org/en/latest/

### PR DESCRIPTION
**Pull request by mohitsaxenaknoldus**
Closes #392

### CODE REVIEW

**Comment by jwmueller** [comment]
@mohitsaxenaknoldus Thanks for the useful PR!!

It seems the current codebase fails the unused-import check, but your check does not tell us which file is failing?
Would you be able to make it print which file is failing so we have more information?  That will also make it easier for our team to review this PR.  Or is that difficult for some reason?

**Comment by mohitsaxenaknoldus** [comment]
> @mohitsaxenaknoldus Thanks for the useful PR!!
> 
> It seems the current codebase fails the unused-import check, but your check does not tell us which file is failing? Would you be able to make it print which file is failing so we have more information? That will also make it easier for our team to review this PR. Or is that difficult for some reason?

@jwmueller Updated the workflow to also print the affected files. By the way, these were your culprit files:

`cleanlab/count.py:31:0: W0611: Unused pandas imported as pd (unused-import)
cleanlab/count.py:34:0: W0611: Unused csr_vstack imported from cleanlab.internal.util (unused-import)
cleanlab/multiannotator.py:3:0: W0611: Unused Optional imported from typing (unused-import)
cleanlab/benchmarking/noise_generation.py:27:0: W0611: Unused import warnings (unused-import)
cleanlab/internal/util.py:569:8: W0611: Unused import tensorflow (unused-import)
cleanlab/token_classification/summary.py:4:0: W0611: Unused Union imported from typing (unused-import)
tests/test_classification.py:22:0: W0611: Unused multivariate_normal imported from numpy.random (unused-import)
tests/test_frameworks.py:33:0: W0611: Unused pandas imported as pd (unused-import)
`

**Comment by jwmueller** [comment]
Looks great to me @mohitsaxenaknoldus!  

It will take a few days for us to merge this PR since we are in the midst of resolving some (unrelated) CI issues. 
In the meantime would you like to help fix the unused imports in the source code files that your CI check has flagged :smile:?

**Comment by mohitsaxenaknoldus** [comment]
> Looks great to me @mohitsaxenaknoldus!
> 
> It will take a few days for us to merge this PR since we are in the midst of resolving some (unrelated) CI issues. In the meantime would you like to help fix the unused imports in the source code files that your CI check has flagged 😄? Could just make these fixes in the same PR, now that it's already proven its utility!

Done.

**Review by elisno — APPROVED** [review]
Awesome stuff, @mohitsaxenaknoldus!
Thank you so much for the PR!


I made some changes:
- Simplify the workflow file by letting pylint handle the errors.
- Switch to pip installation.
- Fix leftover pylint errors/warnings.

**Pull request merged**
