### PR TITLE
Cap `huggingface_hub` and `sklearn` versions to fix Github Page builds

### PR DESCRIPTION
**Pull request by misteroh**
## Summary
Update requirements.txt in `docs` to use a specific version of `huggingface_hub` to fix builds

## Impact

> 🌐 Areas Affected: Enumerate modules, functions, or documentation impacted by your code.

Docs
> 👥 Who’s Affected: Mention who might be impacted (if applicable).

All consumers of documentation

**Screenshots**

> 📸 If your changes modify documentation or a tutorial notebook, please include screenshots or GIFs showing the rendered outputs for a quicker initial review, highlighting the main changes.

n/a

## Testing

> 🔍 Testing Done: Outline what kinds of tests you performed.
>
> 🔗 Test Case Link: Directly link to the most end-to-end check of your new functionality.

PR builds succeed again

**Unaddressed Cases**

> It's ok if your unit tests are not yet
> comprehensive when you first open the PR,
> we can revisit them later!
>
> ⚠️ Mention any aspects of testing that have *not* been covered, and why.

-

## Links to Relevant Issues or Conversations

> 🔗 What Git or Slack items (Issues, threads, etc) that are specifically related to
> this work? Please link them here.

-

## References

> 📚 Include any extra information that may be helpful to reviewers of your
> Pull-Request here (e.g. relevant URLs or Wiki pages that could help give
> background information). 
>
> Share links, docs, or sources that facilitated your changes.
>
> If relevant, please include additional code snippets
> (and their outputs/return values) showing alternative ways to use your newly added methods.

Reference: https://github.com/easydiffusion/easydiffusion/issues/1851

-

### CODE REVIEW

**Review by jwmueller — APPROVED** [review]
thanks for quickfix!

**Comment by misteroh** [comment]
> thanks for quickfix!

of course! some new python error popped up now, I think I'll just wait for Elias to get back for this one as it's a little outside my wheelhouse

**Comment by jwmueller** [comment]
notes for future reference (cc @elisno):

sklearn v1.6 was released Dec 2024, which has new `__sklearn__tags__` attribute that is not compatible with `xgboost` package when the `cross_val_predict` method is called.

https://scikit-learn.org/stable/auto_examples/release_highlights/plot_release_highlights_1_6_0.html


Screenshot 2024-12-09 at 6 17 12 PM

**Comment by jwmueller** [comment]
> > thanks for quickfix!
> 
> of course! some new python error popped up now, I think I'll just wait for Elias to get back for this one as it's a little outside my wheelhouse

Think I fixed it for you by pinning the sklearn version installed in the docs build

**Pull request merged**
