### PR TITLE
Extends non-iid issue check to run if only pred_probs are provided

### LINKED ISSUE #808: extend non-iid issue check in Datalab
Currently Datalab's non-iid issue type is only detected based on `features`:
https://docs.cleanlab.ai/master/cleanlab/datalab/guide/issue_type_description.html#non-iid-issue

If the user does not input `features`, but does provide` pred_probs`, run this same check based on the `pred_probs` instead (just treat them as features). 

Note that if the user did provide `features` or there was already a KNN graph constructed in Datalab, the results should be returned as they currently are, not using the `pred_probs` at all!

Reference:  https://github.com/cleanlab/cleanlab/blob/master/cleanlab/datalab/internal/issue_manager/noniid.py

### PR DESCRIPTION
**Pull request by abhijitpal1247**
Closes #808
Added an additional param for pred_probs in find_issues function and an additional check in non_iid.py file.

### CODE REVIEW

**Review by jwmueller — CHANGES_REQUESTED** [review]
Thanks for the contribution @abhijitpal1247!

To make this easier to review, can you:

Add a basic unit test that evaluates the end-to-end usage of your new issue manager configuration from the Datalab level. Please comment a link to this unit test, so I can also run it myself.

Add a comment to your PR description showing example code to test this new functionality out, and what the output looks like exactly (copy/paste the resulting Datalab `report()` and its `issues`, `issue_summary`, and `info` attributes.

Thanks, we can get somebody to review this PR in more detail once those basics are provided. Then after your code structure has been verified to be good, we'll ask you to add a few more unit tests in order to get the codecov of this new code up to 100%.

**Review by elisno — COMMENTED** [review]
Great work @abhijitpal1247!

The current tests appear solid. However, it would be beneficial to incorporate an end-to-end test case that validates the functionality with either `features` or `pred_probs`. Ensure both pathways operate as expected, particularly from the `Datalab` level rather than the `IssueManager`level.


I've also provided a comment regarding a potential enhancement in the `NonIIDIssueManager.find_issues` method: consider breaking down the code into separate helper functions for improved readability and maintainability.

**Comment by elisno** [comment]
Hi @abhijitpal1247!

Thank you for swiftly putting up new tests! 🚀 
I’d like to discuss a couple of adjustments to align the tests with our conventions for this package.

1. We try out best to keep our tests modular and focused. Let’s move the end-to-end test involving Datalab to `tests/datalab/test_datalab.py` to maintain a clean separation and easy navigation through our test suites. For this PR, just make totally

**Comment by abhijitpal1247** [comment]
@elisno , I have had added changes. Please review it. As we are nearing to the end of hacktoberfest, I would love to get this merge.

**Comment by elisno** [comment]
Hi @abhijitpal1247, this PR is looking solid! I need to do a bit of cleanup, but then it can be merged today.

**Review by elisno — APPROVED** [review]
Great stuff @abhijitpal1247!

The argument handling from the Datalab side had to be configured and some of the end-to-end tests needed to be updated to reflect that.

Some existing tests broke as a result of this:
- Some due to knn_graphs (implicitly based on some feature arrays) have always been prioritized.
  - This broke a test where incremental search would reuse the knn-graph computed from the pred_probs in the NonIIDIssueManager.
  - A short-term solution is just to add a flag to tell the issue manager to avoid storing the knn_graph when necessary. Sure, we use the knn_graph logic, but We still want to assume that most `knn_graph` come from a more general `features` array.
- Previously, we assumed that a Datlab without any labels wouldn't find any issues when passed `pred_probs`, with this PR, these `pred_probs` can be used by the NonIIDIssueManager.

This PR is in a much better state now to merge! Thank you!

**Comment by elisno** [comment]
I'll review the mypy-stuff flagged in the CI in a separate PR.

**Pull request merged**
