### PR TITLE
Add unittest to test_datalab.py 

### LINKED ISSUE #937: add a unit test that `datalab.issues` solely contains numeric and boolean values
Can go in this file:

https://github.com/cleanlab/cleanlab/blob/master/tests/datalab/test_datalab.py

Also add a second unit test that `datalab.issue_summary` solely contains numeric values.

### PR DESCRIPTION
**Pull request by 01PrathamS**
## Summary

> 🎯 **Purpose**: Add unit test to test_datalab.py file
                              1. ```datalab.issues``` solely contains numeric and boolean values.
                              2. ```datalab.issue_summary``` solely contains numeric value

## Links to Relevant Issues or Conversations

Resolves #937

### CODE REVIEW

**Comment by elisno** [comment]
Hi @01PrathamS, thanks for the PR.

Unfortunately, the tests added are flawed. They're directly testing the mocked fields, which defeats the whole purpose of mocking for running tests. 


Please take a moment to review the work more critically before submission. It's important to not only address the issue at hand but also to consider how the contribution genuinely enhances the project. 
Ask yourself if the test being added provides meaningful validation or if it could be refined for greater impact.

**Comment by 01PrathamS** [comment]
hey @elisno thank you for your review, i realize my mistake and after that i read docs, and practice exercises.

can you please review my intuition if i'm not overlooking something. If you feel i'm not understanding things please point me towards documentation, i'm looking forward to your suggestions.

I'm writing this test function under test_datalab.py::TestDatalab 

``` 
def test_get_issues_contains_bool_or_num(self, lab, monkeypatch):
    mock_issues: pd.DataFrame = pd.DataFrame(
        {
            "is_label_issue": [True, False, False, True, False],
            "label_score": [0.2, 0.4, 0.6, 0.1, 0.8],
            "is_near_duplicate_issue": [False, True, True, False, True],
            "near_duplicate_score": [0.5, 0.3, 0.1, 0.7, 0.2],
            "is_class_imbalance_issue": [False, False, False, False, True],
            "class_imbalance_score": [1.0, 1.0, 1.0, 1.0, 0.2],
        },
    )
    monkeypatch.setattr(lab, "issues", mock_issues)

    lab_issues = lab.get_issues()

    for col in lab_issues.columns: 
        assert lab_issues[col].dtype.kind in ['b', 'i', 'u', 'f'], f"Column {col} contains non-numeric/non-boolean values."
```
```
def test_get_issue_summary_contains_num(self, lab, monkeypatch):
    ## first column of the issue be issue name
    mock_summary: pd.DataFrame = pd.DataFrame(
        {
            "issue_type": ["label", "outlier"],
            "score": [0.5, 0.3],
            "num_issues": [1, 2],
        }
    )
    monkeypatch.setattr(lab, "issue_summary", mock_summary)

    lab_issue_summary = lab.get_issue_summary()

    for col in lab_issue_summary.columns[1:]: 
        assert lab_issue_summary[col].dtype.kind in ['i', 'u', 'f'], f"Column {col} contains non-numeric/non-boolean values."
    ```

**Comment by 01PrathamS** [comment]
hello @allincowell can you please help me here , giving me some idea on how do i make this better?

**Comment by jwmueller** [comment]
Closing in favor of: https://github.com/cleanlab/cleanlab/pull/1218

**Pull request closed without merging**
