### PR TITLE
Switch to GitHub Actions

### PR DESCRIPTION
**Pull request by anishathalye**
This patch switches the CI from Travis-CI to GitHub Actions.

The new CI script drops support for Python 3.4 (EOLed 18 March 2019) and Python 3.5 (EOLed 13 September 2020), though it keeps support for Python 2.7 (EOLed 1 January 2020). This keeps the CI configuration a lot simpler.

The new CI script also simplifies code coverage: a single coverage report is produced for Python 3.9 on Ubuntu. There are no coverage statistics being collected and uploaded for older versions of Python 3, Python 2, or other OSes.

### CODE REVIEW

**Comment by anishathalye** [comment]
See here for an example CI run: https://github.com/anishathalye/cleanlab/actions/runs/1450910418

Example coverage report: https://codecov.io/github/anishathalye/cleanlab/commit/7b5782c4d351d4720ec8cb9d435466c2083db578 (same setup as before, still using codecov)

As a bonus, this runs 3x faster than Travis :)

**Comment by cgnorthcutt** [comment]
This is really great work @anishathalye . I'll take a look on Monday

**Comment by cgnorthcutt** [comment]
What would it take to include code coverage for macOS and Windows? Many of our users use Cleanlab on those platforms.

**Comment by anishathalye** [comment]
Done in 023cf45

**Pull request closed without merging**
