### PR TITLE
Improve image tutorial accuracy and finding better label errors

### PR DESCRIPTION
**Pull request by weijinglok**
This PR improves the image tutorial accuracy and finds better examples of label errors. A mockup is available [here](https://weijinglok.github.io/cleanlab-docs/up-img-tut/tutorials/image.html).

### CODE REVIEW

**Comment by jwmueller** [comment]
Please empty the output of cells for this notebook

**Comment by jwmueller** [comment]
How come image tutorial .ipynb kernelspec says "Python 3 (ipykernel)"
but for the audio tutorial .ipynb it only says:   "display_name": "Python 3" ?

**Comment by weijinglok** [comment]
@jwmueller 

> Please empty the output of cells for this notebook

cleared.

> How come image tutorial .ipynb kernelspec says "Python 3 (ipykernel)" but for the audio tutorial .ipynb it only says: "display_name": "Python 3" ?

I've removed the audio tut from this PR.

**Review by jwmueller — APPROVED** [review]
already edited offline

**Pull request merged**
