### PR TITLE
Removed docstrings and rebuilt the docs

### PR DESCRIPTION
**Pull request by ethanotran**
Example of file with docstrings removed:
image

### CODE REVIEW

**Comment by elisno** [comment]
Hi @ethanotran,

Maybe there's a misunderstanding here, but I assume you want to remove ***type annotations*** from the docstrings of functions with typing in their signatures, not the entire docstrings themselves.

**Comment by ethanotran** [comment]
Alright, I'll do that. Apologies for the misunderstanding

**Comment by elisno** [comment]
Another thing: 

Updating the test functions in the `tests/` directory is not as important, as they don't show up on [docs.cleanlab.ai](https://docs.cleanlab.ai/).

Might I suggest that you start with something like https://github.com/cleanlab/cleanlab/blob/fff06759b7741cc1abf5827a347b1032c7a24d22/cleanlab/internal/label_quality_utils.py#L86-L111

**Comment by ethanotran** [comment]
Ok. Can you guys assign issue #453 to me?

**Comment by ethanotran** [comment]
If I go to the test directory and run ./make.bat html. sphinx seems to finish successfully. But if I look at the output html directory, I can't seem to find the generated html file for the various test*.py files in the test directory. Can you give me some instructions on how to point to a specific file for sphinx-build and where to look for the output?

**Comment by elisno** [comment]
> I can't seem to find the generated html file for the various test*.py files in the test directory


This is intended, as we're not trying to build the docs for our unit tests.
You don't have to work on the docstrings in the `test*py` files.

---

> Can you give me some instructions on how to point to a specific file for sphinx-build and where to look for the output?

It looks like you've already gone through the README.md, but I recommend you follow [step 6.ii for building the docs locally](https://github.com/cleanlab/cleanlab/blob/master/docs/README.md#build-the-cleanlab-docs-locally).

For the files that you should be updating, you'd run:

```bash
SKIP_NOTEBOOKS=1 sphinx-build docs/source cleanlab-docs
```

This would build all the documentation, except it won't run any of the tutorial notebooks.

Your html files should be in `cleanlab-docs/`:

<pre>
cleanlab
├── cleanlab
│   ├── ...
│   ├── benchmarking
│   ├── experimental
│   ├── internal
│   └── token_classification
├── cleanlab-docs  
│   ├── ...
│   ├── index.html  <b># Open this file</b>
│   ├── cleanlab
│   ├── migrating
│   └── tutorials
└── docs
    ├── ...
    └── source
</pre>

**Comment by jwmueller** [comment]
Closing in favor of: https://github.com/cleanlab/cleanlab/pull/475

**Pull request closed without merging**
